### ISSUE TITLE
Prompt can't contain []

### ISSUE THREAD

**Issue by codegain** [jcubic/jquery.terminal#648] opened 2021-02-24 11:20 UTC
### Issue summary

Hi,
I'm using 2.22.0 and the following prompt:

```
prompt: '[foobar /]$ ',
```

### Expected behavior

Prompt is
```
[foobar /]$ 
```

### Actual behavior

Prompt is
```
[foobar /$ ]
```
or after pressing Enter, the entered line switches but the prompt stays the same:
```
[foobar /]$ 
[foobar /$ ]
```

### Steps to reproduce

Use a prompt with `[]`.

f.e. in the demo:
```
var term = $('body').terminal(() => {}, {
    'prompt': '[foobar /]$ '
});
```

### Additional info

This worked for me as a workaround in 2.21.0:
```
prompt: '&#x5B;foobar /&#x5D;&#x24; ',
```
f.e. in the demo:
```
var term = $('body').terminal(() => {}, {
    'prompt': '&#x5B;foobar /&#x5D;&#x24; '
});
```
But now this adds big `span` elements after the prompt and after `[` and `]` if Enter is pressed.

### Browser and OS

Chrome 88 on Windows 10

**Comment by jcubic** [comment] 2021-02-24 11:40
Thanks for the bug report, Will investigate.

**Comment by jcubic** [comment] 2021-02-25 16:55
The issue is fixed it will be released in next bug fix version. The problem was that when prompt was not formatting the brackets where not escaped and the whole thing was wrapped in empty formatting, so if fact it was broken formatting. Brackets have special meaning in jQuery Terminal but only if the are in special format (which is know as jQuery Terminal formatting).

**Closed** 2021-04-18 12:34 UTC
Labels: Bug, resolved
