### ISSUE TITLE
Unix formatting for terminal echo

### ISSUE THREAD

**Issue by divyareddy12** [jcubic/jquery.terminal#409] opened 2018-07-05 07:53 UTC
Is it possible to simulate Unix echo formatting for backspaces and escape characters for terminal echo.
 
Example: - 
[Start]]     ---   Done] show be displayed as [Done]

**Comment by jcubic** [comment] 2018-07-05 15:14
you need to include unix_formatting.js file and it will handle escape codes and overtyping (output of man command) but I don't know about the code you provided, ANSI escapes look like this : 

```javascript
term.echo('\x1b[32mfoo')
```

you can test this on codepen https://codepen.io/jcubic/pen/MbVMwO

**Comment by jcubic** [comment] 2018-07-05 15:35
I've copied this to real terminal, my first try was this:
```javascript
$.terminal.defaults.formatters.push([
    /.?\x08/g, ''
]);
```
but it don't work, I'm not sure if it will be possible to make this work.

**Comment by jcubic** [comment] 2018-07-05 16:31
In devel branch you can use:

```javascript
$.terminal.defaults.formatters.unshift([/(^|[^\x08]|\r\n)\x08/g, '', true]);
```

unshift so If you're using unix_formatting it will be before overtyping that handle backspaces. 3 value will indicate that it should create while loop and replacing until regex don't match so don't use same text as regex in replacement, because you will have infinite loop.

The issue with this is that it will not work for command line if you copy paste that text or use insert.

**Comment by jcubic** [comment] 2018-07-06 06:52
I still need to fix the issue with command line rihgt now I'm getting:
```
[Start&#9Done] show be displayed as [Done] 
```
don't know why I have  `[Start&#9` because I've got correct string when from function that do replace in cmd plugin.

I can release 1.17.1 when this is fixed or maybe 1.18.0 because there is new feature.

`$.terminal.defaults` is global you need to have access to jQuery you can put that code where you import jQuery or if you're using script tag you can put it next to main render function where you attach React to DOM.

**Comment by jcubic** [comment] 2018-07-06 07:07
I've menage to fix the issue, the problem was that cmd is escaping brackets before It apply formatters so you can't type formatting into command line.

You will be able to use this regex:
```javascript
$.terminal.defaults.formatters.unshift([/(^|[^\x08]|\r\n|&[^;]+;)\x08/g, '', true]);
```

**Comment by jcubic** [comment] 2018-07-08 07:11
the API changed it will look like this:
```javascript
$.terminal.defaults.formatters.unshift([/(^|[^\x08]|\r\n|&[^;]+;)\x08/g, '', {loop: true}]);
```
3rd argument will be options object or undefined so new options could be added later.

Will release version 1.18.0 probably Today.

**Comment by divyareddy12** [comment] 2018-07-10 07:16
Thank you for your support with backspace.
I have tested with the latest version backspaces is working fine but the last character is not printed(eg: end ']' is not printed). Also when I tried the same for ESC (\u001B[K) it works for the first occurrence but not for the others.

**Comment by jcubic** [comment] 2018-07-10 12:03
is this your question on SO? [Regular expression containing an escape sequence in JavaScript for jquery terminal not working](https://stackoverflow.com/questions/51242807/regular-expression-containing-an-escape-sequence-in-javascript-for-jquery-termin)

I've provided the code with function for backspace

Here is the demo with same code:
https://codepen.io/jcubic/pen/oMvpPZ?editors=0010

one issue with this solution is that cursor dissappear at the end of next line. Will investigate why.

**Comment by jcubic** [comment] 2018-07-10 13:01
The problem is that backspace count as character so formatter change length I will need to update the API to allow for function formatters to return string and position, and will probably add backspace to unix_formatting

**Comment by jcubic** [comment] 2018-07-10 16:20
I've menage to fix the issue, here is new overtyping, you can use it right now if you don't care about command line, for cmd plugin you will need to wait a bit because I need to update the API for formatters and will be much harder to write this formatter with new API because it will need to track position of the cursor track replaces.
```javascript
$.terminal.defaults.formatters.unshift(function overtyping(string) {
    var removed_chars = [];
    function replace(string) {
        // we match characters and html entities because command line escape brackets
        // echo don't, when writing formatter always process html entitites so it work
        // for cmd plugin as well for echo
        var re = /^([^\x08]|[\r\n]{2}|&[^;]+;)\x08/;
        var result = '';
        var push = 0;
        for (var i = 0; i < string.length; ++i) {
            var partial = string.substring(i);
            var match = partial.match(re);
            var removed_char = removed_chars[0];
            if (match) {
                // we remove backspace and character or html entity before it
                // but we keep it in removed array so we can put it back
                // when we have caritage return
                if (match[1]) {
                    removed_chars.push({
                        index: i - match[1].length + push,
                        string: match[1]
                    });
                    return result + partial.replace(re, '');
                }
            } else if (string[i] === '\r') {
                // if newline we need to add at the end all characters removed by backspace
                if (removed_chars.length) {
                    result += removed_chars.map(function(x) {
                        return x.string
                    }).join('');
                    removed_chars = [];
                }
                return result + partial;
            } else {
                if (removed_chars.length) {
                    // if we are in index of removed character we check if the character is the same
                    // it will be bold or if removed char or char at index is underscore then it will
                    // be terminal formatting with underscore
                    if (i > removed_char.index) {
                        if (removed_char.string === string[i] ||
                            removed_char.string === '_' || string[i] === '_') {
                            removed_chars.shift();
                            // if we add special character we need to correct
                            // next push to removed_char array
                            push++;
                            // we use special characters instead of terminal formatting so it's
                            // easier to proccess when removing backspaces
                            if (removed_char.string === string[i]) {
                                result +=  string[i] + '\uFFF1';
                                continue;
                            } else if (removed_char.string === '_' || string[i] === '_') {
                                var chr = removed_char.string === '_' ? string[i] : removed_char.string;
                                result += chr + '\uFFF2';
                                continue;
                            }
                        }
                    }
                }
                result += string[i];
            }
        }
        return result;
    }
    // loop until not more backspaces
    var i = 0;
    while (string.match(/\x08/) || removed_chars.length) {
        string = replace(string);
        if (!string.match(/\x08/)) {
            // we break the loop so if removed_chars still chave items
            // we don't have infite loop
            break;
        }
    }
    function format(string, chr, style) {
        var re = new RegExp('((:?.' + chr +')+)', 'g');
        return string.replace(re, function(_, string) {
            var re = new RegExp(chr, 'g');
            return '[[' + style + ']' + string.replace(re, '') + ']';
        });
    }
    // replace special characters with terminal formatting
    string = format(string, '\uFFF1', 'b;#fff;');
    string = format(string, '\uFFF2', 'u;;');
    return string;
});
```

you still need to include:

```javascript
$.terminal.defaults.formatters.unshift([
    /[^\r\n]+\r\x1B(?:&#91;|\[)K/g, ''
]);
```

**Comment by jcubic** [comment] 2018-07-11 06:32
Fixed overtyping is in devel branch in unix_formatting.js file.

**Comment by divyareddy12** [comment] 2018-07-12 05:03
When would you be releasing the devel branch?

**Comment by jcubic** [comment] 2018-07-12 08:13
Probably in one or two weeks I usually wait a while for new bugs to appear.

I also need to update  unix_formatting functions to return `[string, position]` and update cmd plugin to include new API, because unix formatting only work with echo, it was never working with command line but I want to fix this for next version.

**Comment by divyareddy12** [comment] 2018-07-17 06:44
I updated my unix_formatting.js with the code in devel branch and its not printing the last '[' of each line
String:
 Status.\n\n==============================\nTest1.\t[    ]\b\b\b\b\b--\r\u001B[KTest1.\t[    ]\b\b\b\b\bFAIL\n\r\u001B[KTest2.\t[    ]\b\b\b\b\bSKIP\n\r\u001B[KTEST3.\t[    ]\b\b\b\b\bSKIP\nDuration: 00:00:06\n

With echo -e it gives:
Status.

==============================
Test1.  [FAIL]
Test2.  [SKIP]
TEST3.  [SKIP]
Duration: 00:00:06
 
But in the terminal it is:
Status.

==============================
Test1.  [FAIL
Test2.  [SKIP
TEST3.  [SKIP
Duration: 00:00:06

The formatters is as below:
$.terminal.defaults.formatters.unshift([
            /(^|[^\x08]|\r\n|&[^;]+;)\x08|[^\r\n]+\r\x1B(?:&#93;|&#91;|[\[\]])K|\x1B(?:&#93;|&#91;|[\[\]])K/g, '', {loop: true}
        ]);
Could you let me know how I can correct this

**Comment by jcubic** [comment] 2018-07-17 07:07
Regex will not work with this case, you need to have state to make this work, so only function will work. You will need overtyping function from unix_formatting file for this to work, that handle leftovers before \b when you add \r character. Best is to use whole file. (from_ansi also handle `\x1b[K`).

And if you want this to work when you copy paste that result text (escapes replaced by appropriate characters) into terminal or use `term.insert()`, then you will need to update jquery.terminal as well, but if you only want to work.

**Comment by jcubic** [comment] 2018-07-21 12:30
released in version 1.19.0

**Comment by jcubic** [comment] 2018-07-23 14:52
Silly mistake, it should work now

**Comment by jcubic** [comment] 2018-07-23 16:52
The fix is in version 1.19.1.

**Comment by divyareddy12** [comment] 2018-07-24 18:22
There is another issue with 1.19.1. It skips everything after \b
Example:
Status.\n\n==============================\nTest1.\t[ ]\b\b\b\b\b--\r\u001B[KTest1.\t[ ]\b\b\b\b\bFAIL is displayed as
Status.

==============================
Test1. [ ]

Formatters: $.terminal.defaults.formatters.unshift([/(^|[^\x08]|\r\n|&[^;]+;)\x08/g, '', {loop: true}]);

**Comment by amarendrar** [comment] 2018-07-26 12:42
I have tested the backspace with the latest version and looks like still backspace is not working as expected.

Expected Unix output as below:
----------------------------------------------------------------------------------------

Test0.

==============================
Checking backspace.     [FAIL]
Test1.  [SKIP]
Test2.  [SKIP]
Test3: 00:00:032
Test4
Checking backspace.
----------------------------------------------------------------------------------------

Terminal Output with unix formatting file.

----------------------------------------------------------------------------------------
Test0.

==============================
Checking backspace.    [FAIL
Test1.    [SKIP
Test2.    [SKIP
Test3: 00:00:032
Test4
C]    ]    ]    Checking backspace.
----------------------------------------------------------------------------------------

Code Snippet added in 
[multiply-interpreters-demo.txt](https://github.com/jcubic/jquery.terminal/files/2231933/multiply-interpreters-demo.txt)


```javascript
$.terminal.defaults.formatters.unshift([/[^\r\n]*\r\x1B(?:&#93;|&#91;|[\[\]])K/g, '', {loop: true}]);
		 var data ='Test0.\n\n==============================\nChecking Backspace.\t[    ]\b\b\b\b\b-\r\u001B[KChecking backspace.\t[    ]\b\b\b\b\bFAIL\n\r\u001B[KTest1.\t[    ]\b\b\b\b\bSKIP\n\r\u001B[KTest2.\t[    ]\b\b\b\b\bSKIP\nTest3: 00:00:032\nTest4\n\rChecking Backspace.\t[    ]\b\b\b\b\b-\r\u001B[KChecking backspace.';
term.echo(data);

**Comment by jcubic** [comment] 2018-07-26 15:48
please remove this line:
```javascript
$.terminal.defaults.formatters.unshift([/[^\r\n]*\r\x1B(?:&#93;|&#91;|[\[\]])K/g, '', {loop: true}]);
```

Also there is one issue in unix_formatting, I thought that only \r make text from before backspaces appear after, but it seems it also work with \n, right now only this script works:

```javascript
var data2 ='Test0.\n\n==============================\nChecking Backspace.\t[    ]\b\b\b\b\b-\r\u001B[KChecking backspace.\t[    ]\b\b\b\b\bFAIL\r\n\u001B[KTest1.\t[    ]\b\b\b\b\bSKIP\r\n\u001B[KTest2.\t[    ]\b\b\b\b\bSKIP\r\nTest3: 00:00:032\nTest4\n\rChecking Backspace.\t[    ]\b\b\b\b\b-\r\u001B[KChecking backspace.';
         terminal.echo(data2);
```
`\r\n` instead of `\n\r` and `\r` instead of lonely `\n`

**Comment by jcubic** [comment] 2018-07-26 16:02
one more fix, now \n, \r, \r\n and \n\r works the same and stuff before backspace is added before newline.

**Comment by divyareddy12** [comment] 2018-08-03 10:50
The backspace is working with the new unix_formatting.
I was testing for a different string and there are two ']' printed in some cases.

String: Test 0.\n\n==============================\nTest 1.\t[    ]\b\b\b\b\b--\r\u001B[KTest 1.\t[    ]\b\b\b\b\bDONE\nTest 2.\t[    ]\b\b\b\b\b----\b\b\b\b    \b\b\b\b----\b\b\b\b    \b\b\b\b----\b\b\b\b    \b\b\b\b----\b\b\b\b    \b\b\b\b----\b\b\b\b    \b\b\b\b----\b\b\b\b    \b\b\b\b----\b\b\b\b    \b\b\b\b-\r\u001B[KTest 2.\t[    ]\b\b\b\b\bFAIL\nTest 3.\t[    ]\b\b\b\b\b--\r\u001B[KTest 3.\t[    ]\b\b\b\b\bWARNING]\n\nTest 4\nDuration: 01\nclose

Unix output is as below:
----------------------------------------------------------------
Test 0.

==============================
Test 1. [DONE]
Test 2. [FAIL]
Test 3. [WARNING]

Test 4
Duration: 01
close


Terminal output:
----------------------------------------------------------------
Test 0.

==============================
Test 1. [DONE]
Test 2. [FAIL]
Test 3. [WARNING]]

Test 4
Duration: 01
close

**Comment by jcubic** [comment] 2018-08-08 12:49
The echo and insert work now for this case, but cmd show wrong cursor position when you move the cursor using mouse click.

**Comment by jcubic** [comment] 2018-08-09 17:06
Cursor position is fixed as well, the problem was \t that was displayed as 4 spaces.

**Comment by divyareddy12** [comment] 2018-08-13 04:39
The extra ']' is removed now. Thank you

Another problem I am having is with the import of unix_formatting. 
In case of 'require('jquery.terminal/js/unix_formatting.js');' there is an error that jQouery is not found as unix_formatting loads when the application loads and not when the termimal is opended. Because of this I have extracted unix_formatting locally into a function(unix_formatting) and importing it as 'import { unix_formatter } from './unix_formatting';'
So can unix_formatting be given as an API so that it can be called when the terminal opens and not when the application loads.

**Comment by jcubic** [comment] 2018-08-14 18:06
will add UMD to Unix_formatting the same as for other utility files

**Comment by jcubic** [comment] 2018-08-16 16:05
in 84b6081 I've added UMD for unix_formatting.js, and I just release that I use unix_formatting in node and was working but you needed to define global jQuery variable before you require unix_formatting.

**Comment by jcubic** [comment] 2018-08-19 09:39
version 1.20.0 released with the update.

**Comment by divyareddy12** [comment] 2018-08-20 05:34
Thanks for your support.
1.20.0 is working as expected but the laterst version 1.20.2 the unix formatting is broken again.

**Comment by jcubic** [comment] 2018-08-20 07:59
I've needed to move \x1b[K processing from from_ansi to overtyping because from_ansi needed to be called after overtyping but \x1b[K need to be called before.

**Comment by divyareddy12** [comment] 2018-08-20 08:52
It works now. Thank you

**Comment by jcubic** [comment] 2018-08-21 06:40
version 1.20.3 released.

**Comment by divyareddy12** [comment] 2018-10-22 07:07
For the following the output is in correct. In this case there is only \b and no escape sequence

String: Details statement.\n================================\nLine 1.      [Start]\b\b] \b\b\b\b\b\b    \b\b\b\b--\b\b  \b\bDone]\nLine 2.         [Start]\b\b] \b\b\b\b\b\b    \b\b\b\b-\b \bDone]\nLine 3.    [Start]\b\b] \b\b\b\b\b\b    \b\b\b\b-\b \bDone]\nLine 4.      [Start]\b\b] \b\b\b\b\b\b    \b\b\b\b-\b \bDone]\nLine 5.    [Start]\b\b] \b\b\b\b\b\b    \b\b\b\b----\b\b\b\b    \b\b\b\b----\b\b\b\b    \b\b\b\b----\b\b\b\b    \b\b\b\bDone]\n================================\n\nClosing statement

Unix Output:
```Details statement.
================================
Line 1.      [Done]
Line 2.      [Done]
Line 3.      [Done]
Line 4.      [Done]
Line 5.      [Done]
================================
```
Jquery terminal output:
```Details statement.
================================
Line 1.      [Done]Star] t]
Line 2.         [Done]tar] t]
Line 3.    [Done]tar] t]
Line 4.      [Done]tar] t]
Line 5.    [Done]---    ----    ----    Star] t]
================================
Closing statement
```

**Comment by divyareddy12** [comment] 2018-10-22 09:59
For the below string unix_formatting is broken.
In this case there is only \b and no escape sequence.

String: Details statement.\n================================\nLine 1. [Start]\b\b] \b\b\b\b\b\b \b\b\b\b--\b\b \b\bDone]\nLine 2. [Start]\b\b] \b\b\b\b\b\b \b\b\b\b-\b \bDone]\nLine 3. [Start]\b\b] \b\b\b\b\b\b \b\b\b\b-\b \bDone]\nLine 4. [Start]\b\b] \b\b\b\b\b\b \b\b\b\b-\b \bDone]\nLine 5. [Start]\b\b] \b\b\b\b\b\b \b\b\b\b----\b\b\b\b \b\b\b\b----\b\b\b\b \b\b\b\b----\b\b\b\b \b\b\b\bDone]\n================================\n\nClosing statement

Unix Output:

```================================
Line 1.      [Done]
Line 2.      [Done]
Line 3.      [Done]
Line 4.      [Done]
Line 5.      [Done]
================================
```

Jquery terminal output:

```================================
Line 1.      [Done]Star] t]
Line 2.         [Done]tar] t]
Line 3.    [Done]tar] t]
Line 4.      [Done]tar] t]
Line 5.    [Done]---    ----    ----    Star] t]
================================
Closing statement
```

**Comment by jcubic** [comment] 2018-10-23 06:13
On my Linux box (Fedora/Xfce/bash) I've got this results:

```
String: Details statement.
================================
Line 1.      [Done] 
Line 2.         [Done] 
Line 3.    [Done] 
Line 4.      [Done] 
Line 5.    [Done] 
================================

Closing statement
```

so the spaces before `[DONE]` seems right, I've tried to fix the text after closing bracket.

**Comment by jcubic** [comment] 2018-10-23 06:59
Sorry I don't know how this should be handled I'm having different results each time I echo this in terminal.

1.
```
String: Details statement.
================================
Line 1.      [Done] 
Line 2.         [Done] 
Line 3.    [Done] 
Line 4.      [Done] 
Line 5.    [Done] 
================================

Closing statement
```

2. 
```
String: Details statement.
================================
Line 1.      [Done] 
Line 2.    Done][Star]]
Line 3.    [Done] 
Line 4.      [Done] 
Line 5.    [Done] 
================================

Closing statement
```

3.

```
String: Details statement.
================================
Line Done]tar] 
Line 2Done]ar] 
Line 3Done]ar] 
Line 4Done]ar] 
Done]-----tar] 
================================

Closing statement
```

**Comment by jcubic** [comment] 2018-10-26 07:16
I've tested this in console but it don't work it also don't work in Linux terminal (Fedora/Xfce/bash).

Can you tell me how this should work, what is algorithm for backspaces? Because there are more backspaces then text before, how this suppose to work?

I think that the proper output for:
```
Line 2. [Start]\b\b] \b\b\b\b\b\b \b\b\b\b-\b \bDone]
```
should be:
```
Line 2Done]
```

because there 14 backspaces and only 20 characters without Done so there is left 6 characters so only `Line 2`

Linux terminal is showing:
```
Line 2Done]ar]
```

Because there are 3 backspaces to many.

if you have this instead:
```
echo -e "Line 2. [Start]\b\b] \b\b\b \b\b\b\b-\b \bDone]"
```
the output is:
```
Line 2. [Done]
```

and the same output give jQuery Terminal.

**Comment by jcubic** [comment] 2018-12-07 22:04
Closing because of inactivity and because the input in string is also broken on my Linux machine so I assume that input string is broken. Also didn't got response from OP for a month.

**Closed by jcubic** 2018-12-07 22:04 UTC
