### ISSUE TITLE
Commands not in sync when no system.describe in builtin RPC

### ISSUE THREAD

**Issue by bilogic** [jcubic/jquery.terminal#475] opened 2019-03-17 10:40 UTC
### I have question related to jQuery Terminal

I used fire several ```exec()``` from inside ```onInit()``` in v0.9.3, it worked correctly.
My output was always:
## Output A
```
prompt1>command1
result1
prompt2>command2
result2
prompt3>command3
result3
prompt4>command4
result4
...
```

On dev 2.2.1 using ```exec()```, I'm getting
## Output B
```
prompt1>command1
prompt1>command2
result1
prompt1>command3
result2
prompt1>command4
result3
result4
prompt1>
```

I switch to using ```execHash``` and it worked correctly, i.e. output A

My question is, what is the recommended way to use ```exec()``` so that the output is correct, i.e. output A? Thank you.

**Comment by jcubic** [comment] 2019-03-17 11:48
Is you commands async or they are just echo something?

if you use multiple execs use array:

```javascript
$.terminal.active().exec(['a', 'b', 'a', 'b'])
```

if your commands are async (ajax or setTimeout etc.) you need to use `pause()`/`resume()` (main reason for those functions is not to hide command line, but to have proper timing with exec).

Example:
```
$('???').terminal(function(cmd) {
   term.pause();
   setTimeout(() => this.echo('your commands is ' + cmd).resume(), 1000);
}, {
  onInit: function() {
      this.exec(['command1', 'command2', 'command3', 'command4']);
  }
}
```

this will also work if you call exec one by one:
```javascript
     onInit: function() {
         this.exec('command1');
         this.exec('command2');
         this.exec('command3');
     },
```
NOTE: you can't call `this.exec('cmd1').exec('cmd2');` because exec return a promise that resolve when you call resume.

Instead of resume you can also return a promise from function, but it need to be resolved to undefined otherwise the value will be echoed to terminal, unless this is something you want.

```javascript
        .terminal(function(cmd) {
             if (cmd == 'x') {
                 return $.get('exec.html').then((data) => {
                     this.echo(data.split('\n')[0]); // no return so promise will resolve to undefined
                 });
             } else {
                 this.pause();
                 setTimeout(() => this.echo(cmd).resume(), 500);
             }
         }, {
             onInit: function() {
                 this.exec(['x', 'cmd1', 'cmd2']);
             }
         });
```

The promise is very flexible it only need to be object that have then function, so it work with native Promises or jQuery defereds.

**Comment by bilogic** [comment] 2019-03-17 15:34
Hi,

1. I use a URL string, i.e. ```$('#pjax-main').terminal("{{ url.rpc }}", options);```
2. Both the ```prompt``` and ```result``` are returned via RPC, I suppose that means they are async?

**Comment by bilogic** [comment] 2019-03-17 15:51
Actually, ```execHash()``` does exactly and correctly what I need, but ```exec()``` behaves very differently. Also, I don't see ```execHash()``` using any value for ```setTimeout()```.

Is there a way to run commands using ```exec()``` but have the correct output like ```execHash()```?

**Comment by jcubic** [comment] 2019-03-17 15:58
This should work the same, do you the code somewhere online, where I can test this?

**Comment by bilogic** [comment] 2019-03-17 16:43
Hi,

I have emailed you the links.

**Comment by jcubic** [comment] 2019-03-17 17:00
Not sure what the problem is. Maybe because you don't have system.describe method and different code is executed for rpc interpreter. Will investigate, this seems to be a bug.

**Comment by jcubic** [comment] 2019-03-17 17:09
yes, the problem is `system.describe` if it's not there commands are not in sync. Same happen if you use `ignoreSystemDescribe: true` (which you should use if you don't have system.describe so no extra request at the beginning will happen).

**Comment by bilogic** [comment] 2019-03-17 17:14
Hi,

Thanks! I did add ```describe: false```, in the options earlier, but ```jquery.terminal.js``` it threw an exception and I stopped pursuing. https://terminal.jcubic.pl/api_reference.php indicates that ```ignoreSystemDescribe``` is replaced since 1.5

**Comment by jcubic** [comment] 2019-03-17 17:36
Hm, the original option was not removed to not break existing code (that's why major version was not changed) will need to investigate `describe: false` then.

**Comment by bilogic** [comment] 2019-03-18 01:32
Hi,

2 related questions:

1. Should I open an issue for ```describe: false``` throwing exceptions?
2. What is the purpose of enabling ```system.describe```? i.e. benefits of having it etc

Thank you.

**Comment by jcubic** [comment] 2019-03-18 08:50
If you have system.describe, terminal know RPC methods and can create completion for you. So you can use `completion: true`.

You can crate a bug for exception.

**Comment by jcubic** [comment] 2019-03-18 15:11
Both errors should be fixed.

**Comment by bilogic** [comment] 2019-03-20 03:43
Hi, 

I'm trying to confirm your fixes.

It is weird: my commands are in sync when loaded normally in a browser, but out of sync when loaded in an iframe.

Let me investigate further.

**Comment by bilogic** [comment] 2019-03-20 04:09
I'm using fancybox's iframe. It seems to be the following:

1. insync - click URL => iframe shown => prompt => RPC
2. out of sync - click URL => prompt => RPC => iframe shown

Any idea why this might be so? Thank you.

**Comment by bilogic** [comment] 2019-03-20 04:13
I narrowed it down.

If I bring up chrome's developer tools and ```Disable cache``` is checked, commands intermittently go out of sync. This is done with ```describe: false```

**Comment by bilogic** [comment] 2019-03-20 04:29
Just to add, it seems very hard to replicate out-of-sync in a normal Chrome tab even with ```DevTools``` + ```Disable cache``` checked.

If I load the same link in a fancybox's iframe, out-of-sync happens more frequently.
From initial observation, it seems to happen if first few ```prompt```/```RPC``` completes before the iframe is shown on screen.

Any ideas? Thank you.

**Comment by jcubic** [comment] 2019-03-20 07:48
Will check. I can also add option to exec only when terminal is visible, but this will be workaround, nevertheless it will be useful option.

**Comment by jcubic** [comment] 2019-03-24 17:15
I cannot reproduce, can you provide a demo? the last url/user/passwd don't work:

I was testing using this data uri:

```
data:text/html,<style>body{margin: 0} iframe { display: none} </style><iframe style="width:100%; height: 100%" src="http://localhost/projects/jcubic/terminal/test/manual/exec.html"></iframe><script>window.onload = () => setTimeout(() => document.querySelector('iframe').style.display = 'block', 3000)</script>
```

**Comment by jcubic** [comment] 2019-04-05 09:29
no reply after almost 2 weeks, it should be fixed not possible to reproduce in iframe for new issue.

**Comment by bilogic** [comment] 2019-04-05 09:32
Hi,

Sorry, had other matters on hand. Will update this issue if I find a reliable method to reproduce it. Let's close this for now. Thank you.

**Closed** 2019-04-05 16:34 UTC
Labels: Bug, resolved
