### ISSUE TITLE
Disappearing cursor when using bash keyboard shortcuts

### ISSUE THREAD

**Issue by jarv** [jcubic/jquery.terminal#577] opened 2020-05-27 10:05 UTC
### Issue summary
When using the keyboard shortcuts `CTRL+A`, `CTRL-E` the cursor disappears on the Firefox 76.0.1 browser. 

This bug started happening on version `2.15.1` and is present through the current version `2.16.1`. I've confirmed that version `2.14.1` is ok. Also confirmed that I don't see this bug on Chrome.

Reproduced on http://codepen.io/jcubic/pen/MbVMwO on Firefox 76.0.1 (64-bit), on MacOs Catalina.

**Comment by jcubic** [comment] 2020-05-27 10:39
Thanks for the report, it seems that in Firefox cursor work only when it's at the end of the line. Probably some CSS issue. Will investigate.

**Comment by jcubic** [comment] 2020-05-27 20:25
The issue is fixed on devel branch it will be in next bug fix release probably in the end if the week.

**Closed** 2020-05-31 13:15 UTC
Labels: Bug, resolved
