### ISSUE TITLE
Empty format strings cause missing/wrong output

### ISSUE THREAD

**Issue by sharkdp** [jcubic/jquery.terminal#320] opened 2017-07-01 16:57 UTC
It seems as if empty format strings like `[[b;;]]` are not parsed correctly. I'm using version 1.4.3. It's not a huge problem, but I figured I report this, since it used to work (in version 1.1.2 and possibly later).

By the way: this is a fantastic library!

### Expected behavior

Output
```
1
2
3
4
```

### Actual behavior

Output
```
1
2
]4
```

### Steps to reproduce

Go to http://codepen.io/jcubic/pen/MbVMwO and add these lines:

```js
term.echo('[[b;;]1]\n' +
          '[[b;;]2][[b;;]]\n' +
          '[[b;;]3]\n' +
          '[[b;;]4]');
```

**Comment by jcubic** [comment] 2017-07-01 17:06
Will take a look.

**Comment by jcubic** [comment] 2017-07-01 18:35
the problem was in nested formatting, new feature that allow to use `[[;red;]foo [[;green;]bar] baz]`, the fix is in devel branch (replaced + with * in regex), right now if you want to fix it in your code you can call:

```javascript
$.terminal.defaults.formatters = [];
```

before your create terminal or by using option 

```javascript
{formatters: []}
```

**Comment by sharkdp** [comment] 2017-07-01 18:36
Thank you very much!

**Comment by jcubic** [comment] 2017-07-01 18:43
You can also grab devel version it have also fix for android/firefox/google keyboard but one issue remain (with swipe) that I cannot reproduce.

**Comment by sharkdp** [comment] 2017-07-01 19:02
Thanks. I have a fix for this issue within insect (I simply don't generate any empty format strings, which was never really intended)... so I think I will wait for your next release. No rush! :smile:

**Comment by jcubic** [comment] 2017-07-10 09:30
In version 1.5.0

**Closed by jcubic** 2017-07-10 09:30 UTC
