### ISSUE TITLE
Receiving keydown and keyMap events when paused

### ISSUE THREAD

**Issue by rteshnizi** [jcubic/jquery.terminal#303] opened 2017-03-29 21:18 UTC
### Expected Behavior
This issue is somewhat related to #300.

I would like to be able to add CTRL+C to exit/cancel commands (similar to bash). The issue is that when a command is running, I pause the terminal. That results in suppression of all events by jquery.terminal until it is resumed. Looking at the [code in master branch](https://github.com/jcubic/jquery.terminal/blob/master/js/jquery.terminal.js#L4090), there is a special case in key events to resume terminal on CTRL+D. Is there a way to receive key events while terminal is paused?

### Demo
http://codepen.io/anon/pen/vxQyoO

**Comment by jcubic** [comment] 2017-03-30 07:52
To not change the current behavior of the terminal I would need to add option, maybe `pauseUserEvents: false` and if option is false, you will need to check if terminal is enabled using `term.enabled()`.

**Comment by rht1369** [comment] 2017-03-30 19:00
Adding an option would work fine. I just think when terminal is paused, event's should still be dispatched. The terminal however should not show any output.

**Comment by jcubic** [comment] 2017-03-30 20:03
I added an option `pauseEvents` to both terminal and cmd plugins if it's set to false (default is true) the keymaps and keydown will be fired, I've also fixed the issue with keypress that was executed even if terminal was paused.

It's in master branch it will be in next 1.1.0 version.

**Comment by rht1369** [comment] 2017-03-31 15:53
Thanks for the quick fix. I will make sure to test it out.

**Comment by jcubic** [comment] 2017-04-02 11:42
Let me know if that fix the issue for you, so I can release next version.

**Comment by rteshnizi** [comment] 2017-04-06 16:09
Sorry for the delay here. I tested it and it works fine.

**Comment by jcubic** [comment] 2017-04-06 16:38
Great.

**Comment by rteshnizi** [comment] 2017-04-06 19:36
I just noticed that I cannot override the default CTRL+D behavior (neither in keydown nor in keymap). Can we fix that as well?

http://codepen.io/anon/pen/dvEjKK

**Comment by rteshnizi** [comment] 2017-04-06 19:50
I just noticed that keymap option does not override the default behavior of CTRL+D when terminal is paused since it is handled by key_down [here](https://github.com/jcubic/jquery.terminal/blob/master/js/jquery.terminal.js#L4120). Just wanted to bring this to your attention.

**Comment by jcubic** [comment] 2017-04-06 20:20
There was one issue [typo in cmd options](https://github.com/jcubic/jquery.terminal/blob/acf225ec74db7c651417690cbb1a32aa83e58bd8/js/jquery.terminal-src.js#L879) and I also put keymap before keydown so now keymap have priority.

**Comment by jcubic** [comment] 2017-04-06 21:15
Let me know if that's work for you, the issue is closed but I want to resolve this before I release version 1.1.0.

**Comment by rteshnizi** [comment] 2017-04-06 21:59
Yep, I tested it and it works. Great work!

**Comment by jcubic** [comment] 2017-04-06 22:07
New version is out.

**Comment by rteshnizi** [comment] 2017-04-06 22:08
Awesome!

**Comment by rteshnizi** [comment] 2017-04-06 23:00
@jcubic There is a new issue with keydown now. the even doesn't fire properly.

[Demo](http://codepen.io/anon/pen/ZeNVpX)

**Comment by jcubic** [comment] 2017-04-07 07:35
CTRL+D is handled by both keymap and keydown, keymap for exit from interpreter when not paused and keydown for resuming from pause. So to overwrite exit from interpreter you need this:
```
    keymap: {
        'CTRL+D': function(e) {
            if (this.paused()) {
                this.echo('keymap CTRL+D');
                return false;
            }
        }
    },
```
maybe better will be to have keydown first like before, so you don't get error when you press CTRL+D when pause and when pauseEvents if false.

**Comment by jcubic** [comment] 2017-04-07 09:43
because of #302 I'll restore previous order keydown/keymap.

**Comment by rteshnizi** [comment] 2017-04-07 16:19
I don't think that's a bad idea as long as you mention it in your API documentation. I personally am using keydown. Is the master branch fixed now?

**Comment by jcubic** [comment] 2017-04-07 16:30
not yet, will let you know.

**Comment by jcubic** [comment] 2017-04-09 08:44
I've restored the old order keydown first and keymap second. I'll add section about keyboard in the api reference with info about CTRL+D.

**Comment by jcubic** [comment] 2017-04-09 09:01
I've added keyboard section to api reference page.

**Comment by jcubic** [comment] 2017-04-11 15:58
Version 1.1.1 published, I'm closing the issue.

**Closed by jcubic** 2017-04-11 15:58 UTC
