### ISSUE TITLE
Can't enter text using Firefox on Android with the Google Keyboard

### ISSUE THREAD

**Issue by FLamparski** [jcubic/jquery.terminal#319] opened 2017-06-24 19:57 UTC
### Expected behavior

Text is entered

### Actual behavior

Only some characters/substrings are entered

### Steps to reproduce

See https://github.com/sharkdp/insect/issues/88#issuecomment-310862258

**Comment by jcubic** [comment] 2017-06-25 08:21
Fixed in devel branch, on firefox/google not only keypress but also keydown and keyup don't fire.

**Comment by jcubic** [comment] 2017-06-25 18:19
There is still issue with backspace, I'm working on it.

**Comment by jcubic** [comment] 2017-06-25 19:02
Seems to work, but it require some testing.

**Comment by jcubic** [comment] 2017-06-28 09:20
You can test it here http://terminal.jcubic.pl/android.html

**Comment by FLamparski** [comment] 2017-06-28 09:26
It's much better, there is still some weirdness when swipe-typing though
(words do not appear until another key is pressed or you start another
swipe gesture, at one occasion I had a word not enter in a sequence of
swipe gestures).

**Comment by jcubic** [comment] 2017-06-28 09:33
I've never used swipe gestures, will check this out. Thanks for testing.

**Comment by jcubic** [comment] 2017-06-28 17:42
The problem was that space was not inserted to textarea, when you swipe next word it first insert space (keydown/keypress) and then only input for word.

Can you test again? the same url http://terminal.jcubic.pl/android.html

**Comment by FLamparski** [comment] 2017-06-28 19:28
When swipe-typing a repeating string "foo bar", it only registers every
other word (foo or bar) now. Typing with normal touches is much more
reliable.

**Comment by jcubic** [comment] 2017-06-29 08:14
What should I do to reproduce? I'm using this: tap and move point in one place and then tap and move in different one and the the first one again and I have correct results.

**Comment by FLamparski** [comment] 2017-06-29 08:23
Let's say the string I want to enter is "dog cat dog cat...". I start by
touching 'd' then moving my finger to 'o' then 'g' in one gesture. Then I
lift my finger to start swipe-typing cat the same way. Then repeat. If I
just keep doing that, without using the suggestions bar to confirm what I
typed, I can reliably get the string "dog dog dog..."

Mind you, maybe for some reason the right events just aren't firing - I'd
have to do some tests of my own as it's genuinely intriguing me now.

**Comment by FLamparski** [comment] 2017-06-29 08:24
Mind you, I've noticed some differences between Chrome and Firefox:

**Comment by jcubic** [comment] 2017-06-29 08:25
I've notice the issue with 1st swipe after removing all text with backspace.

**Comment by FLamparski** [comment] 2017-06-29 08:29
![screenshot_20170629-092350](https://user-images.githubusercontent.com/912935/27678505-66ff97c8-5cad-11e7-9941-0590935415b4.png)
![screenshot_20170629-092332](https://user-images.githubusercontent.com/912935/27678513-6ec821fa-5cad-11e7-882b-7de9932ab8a2.png)
Looks like email-to-issue discards attachments

**Comment by jcubic** [comment] 2017-06-29 09:07
this one I cannot reproduce, what version on Android/firefox you're using? I'm using 6.0/54. or maybe it's because you swipe too fast, this one I think I can fix.

**Comment by jcubic** [comment] 2017-07-01 18:52
I've commented out old code that was updating textarea with command, maybe that will fix your issue, it's just shot in the dark, when I've tested it work the same on chrome and firefox, same as before, but maybe it will fix your issue.

**Comment by jcubic** [comment] 2017-07-02 11:52
Can you test again? the same url http://terminal.jcubic.pl/android.html

**Comment by jcubic** [comment] 2017-07-10 09:32
The fix is in version 1.5.0, it work for me. If you have the issues with swipe gestures you can help with info how to reproduce.

**Comment by jcubic** [comment] 2017-08-20 18:41
This is opened without response for about 2 months, it work for me so closing, if you have the same issue and you're willing to test and reproduce, comment and I'll open this issue.

**Closed by jcubic** 2017-08-20 18:41 UTC
