### ISSUE TITLE
Uncaught TypeError When Calling Bunch of ``echo`` in a Loop

### ISSUE THREAD

**Issue by KiddoV** [jcubic/jquery.terminal#878] opened 2023-04-21 18:53 UTC
### Issue summary
I am just printing a bunch of strings line by line to the terminal using ``echo`` and got into this error every time:

```console.log
null:10460  Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at null:10460:59
    at FormatBuffer.forEach (null:1976:17)
    at FormatBuffer.flush (null:1982:14)
    at ready (null:10414:32)
    at DelayQueue.add (null:256:17)
    at null:9364:23
    at jQuery.fn.init.flush (null:10395:17)
    at jQuery.fn.init.flush (null:11486:32)
    at null:10781:42
    at unpromise (null:1136:20)
```

It is pointing to this line number 10460 (line 10390 in the source code) => https://github.com/jcubic/jquery.terminal/blob/ef9b63834a9bc2679fae45fd7d308873304016c3/js/jquery.terminal.js#L10390

I don't think I can re-produce this error. But you can check out the Gif below
![term-error](https://user-images.githubusercontent.com/28552977/233716410-922b02b3-5860-4ff7-9170-0d6dc71dea01.gif)

Noted: all the ``white colored string characters`` come from a  serial COM port.
The weird thing is this error ONLY occurs on the 18th index of the ``for`` loop.
This error cause the terminal to stop receiving data from the ``echo`` method until I type ``clear`` in the terminal then everything works again.

I was hoping you can give me some ideas why is the ``snapshot`` was undefined at that point, so I can track down what causing this in my end.

Thanks,

**Comment by jcubic** [comment] 2023-04-21 19:53
Can you just save the output into a file as a JSON array and send the file? You can also make things easier to remove the COM port from the equation. Just write a simple demo that read the same stuff from a file.

**Comment by jcubic** [comment] 2023-04-21 20:33
I would just try to write code that connect to COM and just use:

```javascript
const output = [];

// save all lines here:
output.push(com_line);

console.log(output);
```

You will see what is the output and you will be able to reproduce the error for instance on CodePen.

The reason why it's better than saving into a file, because you can have undefined values, that may be in the output. If all are text you can save them into a file, or just write or just embed the JSON into the demo.

**Comment by KiddoV** [comment] 2023-04-21 20:44
So do you think that the COM serial sending some weird characters that causing this issue?

**Comment by jcubic** [comment] 2023-04-22 14:30
I need to see the array of strings you're using. This have probably nothing to do with COM port only the specific sequence if lines. To be able to debug this I need to see what you're sending to test terminal and what code you use.

**Comment by jcubic** [comment] 2023-04-22 16:17
I expect that you use `echo(xxxx, { newline: false });` that is causing this issue. This is a feature that was added by one contributor and I'm fixing the issue since the feature was introduced.

**Comment by jcubic** [comment] 2023-04-24 12:12
OK will try to decode your string of numbers into something usable. Will create a reproduction of the issue, I don't understand why you can't do that yourself.

**Comment by jcubic** [comment] 2023-04-24 12:19
Is this correct? https://codepen.io/jcubic/pen/ExdWgqY?editors=1010 I don't see any errors.

Again, please create a reproduction of the error. I can't debug your vague description.

**Comment by jcubic** [comment] 2023-04-24 13:35
I don't see any error in your codepen demo. The backend doesn't matter the problem is on the frontend, if you have a sequence of lines that you echo you only need to save that somehow. You have to send something else. The gif in the first post has colors, that are missing on your bytes sequence.

Maybe try to publish your code somehow so I can see the error. If I don't see the error I can help you.

**Comment by jcubic** [comment] 2023-04-27 17:54
If you can't provide reproduction can you at least provide full application that I can test?

**Comment by KiddoV** [comment] 2023-04-27 18:20
This actually the app I commented here: https://github.com/jcubic/jquery.terminal/issues/849#issuecomment-1523252356
But I don't think you can run it because it required a serial COM port device, which you don't have.

I will find a way to re-produce this 🤔

**Comment by jcubic** [comment] 2023-07-12 19:08
I've found a bug in the code that uses the snapshot variable inside the flush method. If you still working on your app you can give it a try with devel version of the library.

If that doesn't help it may require debugging the library itself and finding the root cause of the issue. Unless you will be able to provide a reproduction of the issue.

**Comment by KiddoV** [comment] 2023-07-13 00:06
It has been awhile since I work on this app. I will give it a try when I have time.
Thanks!

**Comment by KiddoV** [comment] 2023-09-15 14:03
I am still getting this error on ``v2.37.1`` unfortunately. :(

**Comment by jcubic** [comment] 2023-09-15 16:04
@KiddoV Nothing has changed and I still need to see a reproduction.

**Comment by lingyunzhimeng** [comment] 2024-01-31 09:18
Hey man, this time has passed, I wonder if you have any new thoughts on this bug, unfortunately I encountered it. Fortunately, I modified your code above and reproduced the bug.

```
function formatRender(textColor, data, bold) {
    return bold ? `[[b;${textColor};]${data}]` : `[[;${textColor};]${data}]`;
  }
const term = $('body').terminal(() => {}, {
      greetings: '',
      name: 'fdsaf',
      outputLimit: 5,
      wrap: false,
      isSupportCopyImg: false,
      pasteImage: false,
});
term.set_prompt(formatRender('#404040', 'WB>', true));
const lines = "[97][116 13 13 10 13 10 79 75 13 10 13 13 10][97][116 116 13 13 10][67][111 109 109 97 110 100 32 110 111 116 32 102 111 117 110 100 33 13 10 13 10 69 82 82 79 82 13 10 13 13 10][97][116 105 13 13 10 77 117 108 116 105 84 101 99 104 32 120 68 111 116 13 10 70 105 114 109 119 97 114 101 32 58 32 52 46 49 46 53 45 100 101 98 117 103 45 109 98 101 100 54 48 56 48 48 13 10 76 105 98 114 97 114 121][32][32 58 32 52 46 49 46 51 45 100 101 98 117 103 45 109 98 101 100 54 48 56 48 48 13 10 77 84 83 45 76 111 114 97 32 58 32 52 46 49 46 51 45 100 101 98 117 103 45 109 98 101 100 54 48 56 48 48 13 10 13 10][79][75 13 10 13 13 10][97][116 43 100 105 63 13 13 10][48][48 45 56 48 45 48 48 45 48 48 45 48 48 45 102 102 45 102 102 45 102 102 13 10 13 10 79 75 13 10 13 13 10]".split('][').map(line => {
    line = line.replace(/[[\]]/g, '');
    return line.split(' ').map(str => {
        return String.fromCharCode(+str);
    }).join('');
}).forEach(line => {
    term.echo(line, { newline: false });
});

github('jcubic/jquery.terminal');
```

> @KiddoV Nothing has changed and I still need to see a reproduction.

**Comment by lingyunzhimeng** [comment] 2024-01-31 09:22
> Hey man, this time has passed, I wonder if you have any new thoughts on this bug, unfortunately I encountered it. Fortunately, I modified your code above and reproduced the bug.
> 
> ```
> function formatRender(textColor, data, bold) {
>     return bold ? `[[b;${textColor};]${data}]` : `[[;${textColor};]${data}]`;
>   }
> const term = $('body').terminal(() => {}, {
>       greetings: '',
>       name: 'fdsaf',
>       outputLimit: 5,
>       wrap: false,
>       isSupportCopyImg: false,
>       pasteImage: false,
> });
> term.set_prompt(formatRender('#404040', 'WB>', true));
> const lines = "[97][116 13 13 10 13 10 79 75 13 10 13 13 10][97][116 116 13 13 10][67][111 109 109 97 110 100 32 110 111 116 32 102 111 117 110 100 33 13 10 13 10 69 82 82 79 82 13 10 13 13 10][97][116 105 13 13 10 77 117 108 116 105 84 101 99 104 32 120 68 111 116 13 10 70 105 114 109 119 97 114 101 32 58 32 52 46 49 46 53 45 100 101 98 117 103 45 109 98 101 100 54 48 56 48 48 13 10 76 105 98 114 97 114 121][32][32 58 32 52 46 49 46 51 45 100 101 98 117 103 45 109 98 101 100 54 48 56 48 48 13 10 77 84 83 45 76 111 114 97 32 58 32 52 46 49 46 51 45 100 101 98 117 103 45 109 98 101 100 54 48 56 48 48 13 10 13 10][79][75 13 10 13 13 10][97][116 43 100 105 63 13 13 10][48][48 45 56 48 45 48 48 45 48 48 45 48 48 45 102 102 45 102 102 45 102 102 13 10 13 10 79 75 13 10 13 13 10]".split('][').map(line => {
>     line = line.replace(/[[\]]/g, '');
>     return line.split(' ').map(str => {
>         return String.fromCharCode(+str);
>     }).join('');
> }).forEach(line => {
>     term.echo(line, { newline: false });
> });
> 
> github('jcubic/jquery.terminal');
> ```
> 
> > @KiddoV Nothing has changed and I still need to see a reproduction.

At present, it seems that it is affected by outputLimit, but if I configure this limit but it is less than the total number of rows that may be displayed, will it not work?

**Comment by jcubic** [comment] 2024-01-31 12:24
This [Codepen](https://codepen.io/jcubic/pen/qBvxgKW?editors=0010) fails successfully.

This is something I can investigate, thanks again for the reproduction.

**Comment by jcubic** [comment] 2024-01-31 13:34
The issue is fixed, Please don't close it. I keep it open until it's released.

**Comment by lingyunzhimeng** [comment] 2024-02-01 03:22
> The issue is fixed, Please don't close it. I keep it open until it's released.
I'm very glad that you have solved this bug. When is the fix expected to be released?

**Comment by KiddoV** [comment] 2024-02-01 03:37
Nice job guys!

**Comment by jcubic** [comment] 2024-02-01 11:54
I have a bunch of fixes and features on the devel branch. So I think that I can release now.

**Closed** 2024-02-01 12:03 UTC
Labels: Bug, resolved
