### ISSUE TITLE
Typing issue with dead keys enabled

### ISSUE THREAD

**Issue by sharkdp** [jcubic/jquery.terminal#329] opened 2017-08-27 15:32 UTC
### Expected behavior
See `pi r^2` on the screen.
(Actually: I hope this is the expected behavior - this is what happens in Internet Explorer)

### Actual behavior
See `pir^2` on the screen.

### Steps to reproduce
- Go to http://terminal.jcubic.pl/#demo
- Type `p`, `i`, `<SPACE>`, `r`, `^`, `2`.

### Browser and OS

- Windows 7
- Google Chrome 60.0.3112.113 (official build) (64-Bit)
- "Dead keys" enabled, i.e. typing `^` and `e` leads to `ê`.

**Comment by jcubic** [comment] 2017-08-27 16:04
How to enable dead keys, do you use keyboard layout that have them? if yes which layout?

**Comment by sharkdp** [comment] 2017-08-27 16:13
I'm using the German keyboard layout on Windows. I think "dead keys" should be enabled by default with the German layout ([Source](https://superuser.com/q/280005)).

**Comment by jcubic** [comment] 2017-08-27 18:19
I'm not able to reproduce. I'm using `German (Germany)` layout and in chrome /windows7 I've got your expected behavior.

Do you have space that got removed when you type 2 or it don't get echoed?

PS: I've found different issue the input event was not fired when terminal was enabled and inserted  to DOM after it was created (I still have demo with detatch/attach that I was testing and in it input was not fired).

**Comment by sharkdp** [comment] 2017-08-27 19:33
> Do you have space that got removed when you type 2 or it don't get echoed?

More like the first option:


1. I type `pi r`. Everything is displayed correctly:

![image](https://user-images.githubusercontent.com/4209276/29753293-bb18ab48-8b6e-11e7-884c-cbd9be587435.png)

2. I type `^`. Nothing changes visually (because it's a dead key)

3. I type `2`. Now it looks like this:

![image](https://user-images.githubusercontent.com/4209276/29753302-ed5b46a6-8b6e-11e7-9534-e9a9a2c3bae7.png)


> I'm not able to reproduce. I'm using German (Germany) layout and in chrome /windows7 I've got your expected behavior.

Hm.. but dead keys are enabled (nothing is displayed when you type `^`)?

---

By the way: enabling dead keys is not something I normally do - it's horrible ;-). It's just the standard on Windows for the German keyboard.

**Comment by sharkdp** [comment] 2017-08-27 19:41
Some more observations
- Typing `r^2` works as expected
- Typing `pi r`, then `^`, **then `<space>`**, then `2` works as expected

**Comment by jcubic** [comment] 2017-08-27 20:15
when I test again, probably by that other fix with auto enable, I've reproduced the issue. The fix is in dev, can you check this [codepen](https://codepen.io/jcubic/pen/LxgJQG)?

**Comment by jcubic** [comment] 2017-08-27 20:16
There was code that prevented input event for space in keypress. I hope it will not break other things like Android, will test it tomorrow.

**Comment by sharkdp** [comment] 2017-08-27 20:29
> The fix is in dev, can you check this codepen?

Nice! Works!

(I've said this previously, but your response time is incredible! Keep up the good work!)

**Comment by jcubic** [comment] 2017-08-28 07:29
It work on Android without problems will publish 1.6.3

**Closed** 2017-08-29 10:04 UTC

**Comment by sharkdp** [comment] 2017-08-29 20:03
Thank you very much!
