### ISSUE TITLE
weird behavior when using more than one terminal

### ISSUE THREAD

**Issue by jsaray** [jcubic/jquery.terminal#742] opened 2022-02-04 15:29 UTC
Hi, 
I am using your plugin with three terminals coordinated.
When I append some data to them, they start vibrating undefinitely.
This behavior only appears in firefox, chromium do not have it.

Any ideas what the problem could be ?.

Best regads,

**Comment by jcubic** [comment] 2022-02-04 17:09
Can you create a demo, that reproduces the issue? It's hard to say from the description.

**Comment by jsaray** [comment] 2022-02-07 10:35
ok, I will provided one soon.
Thanks.

**Comment by jcubic** [comment] 2022-02-11 23:34
If you have a problem creating a demo, maybe you can publish your app online somewhere if you don't have that already. And if you can't share your app publicly you can send it to me an email.

**Comment by jsaray** [comment] 2022-02-18 17:06
could you please send me your email address ?

**Comment by jcubic** [comment] 2022-02-18 20:25
I have an email public on my profile [@jcubic](https://github.com/jcubic).

**Comment by jsaray** [comment] 2022-02-22 13:23
just seen proof of the bug. Best

**Comment by jsaray** [comment] 2022-02-22 13:23
it seems is related with all consoles having the same time to refresh, if you change the time you dont see anymore the behavior

**Comment by jcubic** [comment] 2022-02-22 18:24
I don't see any issue on Firefox, except the horizontal scrollbar (this is a bug in Firefox that I've reported [here](https://webcompat.com/issues/100045)).

I can only see a bit of flicker on Chrome, but it's probably because you don't have height set. This may be an issue with rendering and event loop. Why don't you just use different timing?

**Comment by jcubic** [comment] 2022-02-22 18:37
I can only guess but it maybe related to this code:
```javascript
                        self.stopTime('flush').oneTime(1, 'flush', function() {
                            css(self[0], {
                                '--terminal-height': self.height(),
                                '--terminal-x': offset.left - self_offset.left,
                                '--terminal-y': offset.top - self_offset.top,
                                '--terminal-scroll': self.prop('scrollTop')
                            });
                            // Firefox won't reflow the cursor automatically, so
                            // hide it briefly then reshow it
                            cmd_cursor.hide();
                            self.oneTime(1, 'flush', function() {
                                cmd_cursor.show();
                            });
                        });
```

inside Flush, so it may happen if you call flush 3 times on 3 terminals. The first is executed the second call will wait for the first to finish. So 2nd terminal needs to wait for 2 even loops cycles.

I'm not sure how to fix this. I would need to create some kind of scheduler for the flush timer, it will be really complex. It would be easier if you just don't call multiple echo on different terminals at the same time.

Do you have any use-case when this is a real problem?

**Comment by jcubic** [comment] 2022-02-22 18:44
It seems that removing code for firefox solves the issue for Chrome.

If the issue happens in Firefox you need to provide better reproduction.
Also what OS you're using, I've tested it in Fedora and it works fine.

**Comment by jcubic** [comment] 2022-02-22 19:17
Ok, I know what is the issue. When the terminal doesn't have height it's resized and it triggers a redraw of all lines on each echo. I can check If I can limit redraw only to change in width.

If you set a fixed height it will work as expected, please check if it works when the terminal has height. If it will fix your issue, the fix should be easy.

**Comment by jcubic** [comment] 2022-02-22 20:15
I've tried multiple things:
* make redraw happen only when width change
* add flush_queue that triggers flush in setTimeout
* DIsable modification of DOM in the flush 
* Changing `contain` to `initial`

Noting is working, I don't anything can be done here. I can only optimize redraw that is calling multiple times for no reason.

**Comment by jsaray** [comment] 2022-02-22 20:34
Hi, thanks for your feedback, as stated above I could fix it by setting different timers.
Thanks for the plugin. It rocks !.

**Comment by jcubic** [comment] 2022-02-28 20:36
Ok so I will close this.

**Closed by jcubic** 2022-02-28 20:36 UTC
Labels: Bug
