### ISSUE TITLE
Modifications made to terminal-output DOM node disappear on resize

### ISSUE THREAD

**Issue by ovk** [jcubic/jquery.terminal#326] opened 2017-08-06 22:47 UTC
### Expected behavior
Any modifications (i.e. added child nodes) of `terminal-output` DOM node are persistent.

### Actual behavior
Added nodes removed on terminal windows resize.

### Steps to reproduce
Example: https://jsfiddle.net/txgg52fa/5/
Type any command and hit enter. A command label *Some Label* will appear right from command. Resize window: label disappears.

It doesn't matter whether child node appended in `onAfterCommand` or in command callback itself.

### Browser and OS
Ubuntu 16.04, Chrome 60.0.3112.90

**Comment by jcubic** [comment] 2017-08-07 05:10
This is expected behavior, terminal-output is cleared before each redraw. The only way to have persistent DOM changes is to use finalize echo option which is a function that's passed DOM node or jQuery object of the container as argument (don't remember which one right now and I can't test because I'm not next to my computer) 07.08.2017 12:47 AM Oleg <notifications@github.com> napisał(a):Expected behavior
Any modifications (i.e. added child nodes) of terminal-output DOM node are persistent.
Actual behavior
Added nodes removed on terminal windows resize.
Steps to reproduce
Example: https://jsfiddle.net/txgg52fa/5/
Type any command and hit enter. A command label Some Label will appear right from command. Resize window: label disappears.
It doesn't matter whether child node appended in onAfterCommand or in command callback itself.
Browser and OS
Ubuntu 16.04, Chrome 60.0.3112.90

**Comment by ovk** [comment] 2017-08-07 14:09
@jcubic, using `echo` version that accepts a callback, or using `raw` echo option is indeed preserves changes. The problem, is that this way you can only modify the "output" part of the DOM.

For instance, for my application I need to generate clickable labels for each command user enters. In the jsfiddle example I posted before, I did this by appending child to `.command div` node, which works fine, but disappears on resize. I could also see many other potential use cases, that rely on modifying DOM on certain conditions. I think there should be a way to modify DOM in a way that jquery.terminal preserves this changes.

**Comment by jcubic** [comment] 2017-08-07 14:20
The library need to clear the output before rerender, maybe I can add callback option that will be passed to echo command. 07.08.2017 4:09 PM Oleg <notifications@github.com> napisał(a):@jcubic, using echo version that accepts a callback, or using raw echo option is indeed preserves changes. The problem, is that this way you can only modify the "output" part of the DOM.
For instance, for my application I need to generate clickable labels for each command user enters. In the jsfiddle example I posted before, I did this by appending child to .command div node, which works fine, but disappears on resize. I could also see many other potential use cases, that rely on modifying DOM on certain conditions. I think there should be a way to modify DOM in a way that jquery.terminal preserves this changes.

**Comment by ovk** [comment] 2017-08-07 14:58
Yeah, I saw that redraw in the library code. Maybe a global callback would be easier to implement (something like `onAfterRedraw` or `transform`) and it will allow user to apply necessary DOM modifications after redraw.

**Comment by jcubic** [comment] 2017-08-07 15:35
I think I can add both onAfterRender and onEchoCommand. I think the second one will be better for your case because you will not need to add label to previous commands. 07.08.2017 4:58 PM Oleg <notifications@github.com> napisał(a):Yeah, I saw that redraw in the library code. Maybe a global callback would be easier to implement (something like onAfterRedraw or transform) and it will allow user to apply necessary DOM modifications after redraw.

**Comment by jcubic** [comment] 2017-08-08 17:42
Add `onEchoCommand` and `onAfterRedraw` events in devel branch, they will be in next version 1.6.0.

**Comment by jcubic** [comment] 2017-08-10 12:57
version 1.6.0 is out.

**Closed by jcubic** 2017-08-10 12:57 UTC
