### ISSUE TITLE
CTRL+V sometimes paste whole line instead what's in the clipboard

### ISSUE THREAD

**Issue by artursOs** [jcubic/jquery.terminal#336] opened 2017-09-19 08:02 UTC
### Expected behavior
output what is in buffer
### Actual behavior
outputs again set_command string
### Steps to reproduce
set_command('test') . ctrl-v will output "test" instead of what is in buffer
### Browser and OS
chrome/ffox

**Comment by jcubic** [comment] 2017-09-19 09:12
what you mean by buffer, a clipboard?

I cannot reproduce I've copied `"terminal"` to clipboard and when I've press CTRL+V I've got `"testterminal"`
see 
https://codepen.io/jcubic/pen/BwBYOZ

type `test <enter> CTRL+V`

**Comment by artursOs** [comment] 2017-09-19 09:56
yes, clipboard. first you need to use set_command('test')  then press ctrl - v -  it will output not what is stored in clipboard, but  what was printed with set_command.

**Comment by artursOs** [comment] 2017-09-19 10:03
strange , i just tested on the link you provided. maybe it's not set_command()... but when you focus on command line with mouse click and press ctrl-v, sometimes it pastes clipboard result,but some times it pastes whole command string from the start.

**Comment by jcubic** [comment] 2017-09-19 16:58
can you tell me exact steps to reproduce the issue?

**Comment by artursOs** [comment] 2017-09-20 14:20
i do not have red promt. i must apologize about set_command... it was problem on my side. But sometimes ctrl-v clones whole command instead of pasting what's in clipboard. But it happens when performing quick ctrl+v. So maybe it's not that critical.

**Comment by jcubic** [comment] 2017-09-20 14:35
Ok, I've got it after focusing and pasting few times I got whole line will try to fix the issue.

**Comment by jcubic** [comment] 2017-09-20 17:14
There was some race condition, should be working now in devel branch.

**Comment by jcubic** [comment] 2017-09-24 09:30
Released in version 1.8.0

**Closed by jcubic** 2017-09-24 09:30 UTC
