### ISSUE TITLE
Typing < or > might glitch the cursor

### ISSUE THREAD

**Issue by Codezigineer** [jcubic/jquery.terminal#682] opened 2021-08-23 05:07 UTC
### Issue summary
Typing < or > might glitch the cursor.
### Expected behavior
Should be able to delete < and > perfectly
### Actual behavior
Doesn’t delete the < or > and glitches a bit
### Steps to reproduce
Just make a terminal and some text, type < or > and keep backspacing.
### Browser and OS
Safari on MacOS

**Comment by jcubic** [comment] 2021-08-23 07:09
I cannot reproduce, I've tested on Fedora/Chrome and Safari/MacOS (using BrowserStack).
Do you use any extensions? Maybe XML formatting or some other formatter? Do you have an online demo maybe?

**Comment by jcubic** [comment] 2021-09-09 05:10
I'm closing this issue as invalid if you think this is really an issue please reopen and create a reproduction demo.

**Closed by jcubic** 2021-09-09 05:10 UTC
