### ISSUE TITLE
Using prism with react and npm

### ISSUE THREAD

**Issue by Kingsy** [jcubic/jquery.terminal#624] opened 2020-09-17 21:54 UTC
### I have question related to jQuery Terminal

Hi, so I am looking into using jquery terminal on a nextjs react application.
I have installed jquery and jquery.terminal via npm, all works great and I have rendered the terminal in a component using the library via import statements. 
However when wanting to add code highlighting support, I added Prism via npm but the following global function -> https://unpkg.com/jquery.terminal/js/prism.js currently fails.

it is not available via npm, and when simply included via next/head as a regular <script> tag, the jquery and $.terminal objects are not available as they have not been important.

Could you advise on how to get prism working with jquery.terminal in this situation?

Thanks

Chris

**Comment by jcubic** [comment] 2020-09-18 07:03
Can you share example code? The file prism.js is in npm (here is the link that fetch files from npm: https://cdn.jsdelivr.net/npm/jquery.terminal/js/prism.js)

You will need to impor the prism and call it you should call it with jQuery object:
```javascript
import jquery from 'jquery';
import terminal from 'jquery.terminal';
import prism from 'jquery.terminal/js/prism.js';
prism(window, $); // prism will be loaded automatically
```
You will also need to import any Prism theme CSS file, if you want best workings you should use package `terminal-prism` that have monkey patches of Prism CSS files.

If you will have problems please provide example application that I can test.

**Comment by jcubic** [comment] 2020-09-18 19:01
And also you will need to call the prism function, the easiest is to call `$.terminal.syntax('language');` and if the language is not loaded by default you will also need to load the language from prism, this will require to load prism first, actually I've never imported PrismJS from npm using webpack, If you will have issue I can try to create demo that I will link in docs.

**Comment by Kingsy** [comment] 2020-09-24 19:29
Hi, so after having a look you are absolutely right, the prism stuff is included, but I am having real trouble getting it to work at all.

If I just 

import jquery from 'jquery';
import terminal from 'jquery.terminal';
import prism from "jquery.terminal/js/prism.js";

The documentation states to use it as so.

$.terminal.syntax('python')

Where do you actually pass the python in? Also why the use of the $ for jquery? Wouldnt you just call it like terminal.syntax ?
And on that note does the formatted text get returned at some point?

A really simple example would be good if thats possible, as simple as possible using the npm modules.

**Comment by jcubic** [comment] 2020-09-25 07:23
If you imported jQuery as jquery then you need:

```
jquery.terminal.syntax('python');
```
Note that pyton will require to load the language, check https://prismjs.com/ how to import the language.

**Comment by Kingsy** [comment] 2020-09-25 08:42
import jquery from 'jquery';
import terminal from 'jquery.terminal';
terminal(window, jquery);
import prism from 'jquery.terminal/js/prism.js';
prism(window, jquery); // prism will be loaded automatically

So after all of this, you use it as so.

jquery.terminal.syntax('python');

Then regardless of the string you inject into 

term.echo("Some code"); it will syntax highlight as python?

If so how do you turn it off?

Say I only wanted to highlight 4 echo statements then return to normal?

**Comment by jcubic** [comment] 2020-09-25 09:21
what syntax does is adding new formatter, you can disable formatters using `term.echo('Some text", {formatters: false});` and it will not sure any formatters that would be added.

**Comment by Kingsy** [comment] 2020-09-25 09:27
Ah ok, so on that note.

term.echo('Some text", {formatters: 'python'});

Would echo with python highlighting?

**Comment by jcubic** [comment] 2020-09-25 09:33
no `term.echo('Some text')` will format python. Formatters are global array if functions or arrays [regex, function]. If you add formatter to that list it will always be active. So you don't need to do any extra things to have python code. But note that you will need also CSS from prismJS without CSS whole code will be in same color (it will only have different classes on tokens).

**Comment by Kingsy** [comment] 2020-09-25 18:56
Sorry after having a closer look here I am still not getting there :(.

I am using this with npm in nextjs, so its React. there is no window object for use in the component. or at least for SSR. 

Server Error
ReferenceError: window is not defined

**Comment by jcubic** [comment] 2020-09-25 19:53
Sorry I'm not sure window object is requirement for jQuery. If you want to use on the server you need to use jsDom to get window object. This is how old unit tests was created now when I use jest framework the jsDom is build it.

**Comment by Kingsy** [comment] 2020-09-25 23:20
My fault. I am just not confident with these technologies, different question then, what do the follow do?

terminal(window, jquery);
prism(window, jquery);

if I am importing jquery, and terminal, why cant I just run jquery.terminal.syntax('python');

and omit the above?

**Comment by jcubic** [comment] 2020-09-26 09:54
This will execute the actual code, like main function in C. This is how old jQuery was created. When using from Webpack you needed to call it with window object and you would not have jQuery object at all until you do that, you would have small UMD function in jquery and you needed to have something like this:
```
import jQueryInit from 'jquery';
const jquery = jQueryInit(window);
```
My library didn't change that code, maybe I can do something about this. The problem is that you jQuery instance you can just import jQuery inside jqueryTerminal and prism because jQueryTermina will have different instance than Prism.

**Comment by Kingsy** [comment] 2020-09-28 23:08
Thanks for this,. I am getting closer.

So the problem was the window object was not available outside of the componentDidMount function.

However now I get the following error

Unhandled Runtime Error
TypeError: jquery_terminal_js_prism_js__WEBPACK_IMPORTED_MODULE_11___default() is not a function

On this line

prism(window, jquery);

Something else I am missing?

**Comment by Kingsy** [comment] 2020-09-28 23:15
Update: I managed to get it imported with

import prism from "../node_modules/jquery.terminal/js/prism.js";

However new error

Server Error
TypeError: $.extend is not a function

Coming from prism.js

**Comment by jcubic** [comment] 2020-09-29 06:37
Will try to create demo application with all extensions included, will use it as example.

**Comment by Kingsy** [comment] 2020-09-29 08:05
Thank you! That would be much appreciated.

The framework I am using is nextjs if you want to try and reproduce, nothing special apart from that.

**Comment by jcubic** [comment] 2020-09-29 09:48
The framework should not matter only webpack and importing files.

**Comment by jcubic** [comment] 2020-09-29 17:55
I was little busy and didn't created demo yet. But just realized that I didn't mention that there is [Webpack section in Getting Started](https://github.com/jcubic/jquery.terminal/wiki/Getting-Started#webpackes6babel) did you check that?

**Comment by Kingsy** [comment] 2020-09-30 08:06
No problem, take your time.
Ah, well I actually think the terminal() call in my case works - or at least does not error. Its the prism.js call - prism() that seems to throw the error.

**Comment by jcubic** [comment] 2020-09-30 17:06
After some struggle I was able to create demo with Prism working.

https://github.com/jcubic/terminal-webpack-prism

It require to load prism first and use prism babel plugin so you can load the language in webpack.

**Comment by Kingsy** [comment] 2020-09-30 19:24
Thanks so much for this. Unfortunately it still does not work for me, but this time it is nextjs related specifically. it seems that components/terminal.js loads ./node_modules/jquery.terminal/css/jquery.terminal.min.css, and nextjs does not allow that.

Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).

So I'm stuck.

**Comment by jcubic** [comment] 2020-09-30 19:48
What about if you do, what error say. Import css from App component. There should be lot of examples that show how to do that.

**Comment by Kingsy** [comment] 2020-09-30 19:58
Isnt the error happening because its being imported by terminal.js?
Simply including the .css from within the app wont help if the import statement is still in the .js file right? ermm i can try though

**Comment by Kingsy** [comment] 2020-09-30 20:54
Thanks so much.
This works. I had to do a bit of shuffling things around due to nextjs. 

Apologies for the confusion on the css file. I didn't realise I was copying it over with the import statements. My fault.

Really appreciate your effort on this. I don't think I ever would have known to add the babel plugin to include the language that way. amazing.

**Comment by Kingsy** [comment] 2020-09-30 20:54
Sorry, I closed given this is resolved now.

**Comment by Kingsy** [comment] 2020-09-30 21:03
Actually, one more question, if i add multiple formatters as so.

        $.terminal.syntax('python')
        $.terminal.syntax('bash')

Can I select them like this

       term.echo(result, {formatters: 'bash'});

or 

        term.echo(result, {formatters: 'python'});

I am guessing thats how I would do it?

**Comment by jcubic** [comment] 2020-10-01 07:01
No if you want multiple formaters and always use echo you can use:
```javascript
term.echo($.terminal.prism('bash'. 'result'));
```
and don't call syntax. You can also use bind to create curry function:
```javascript
const bash = $.terminal.prism.bind(null, 'bash');
const python = $.terminal.prism.bind(null, 'python');
```

formatters was created so every echo and CMD is changed to colors, mostly so you can have highlighting why you type.

PS: About that babel plugin it's in PrismJS documentation at [PrismJS home page](https://prismjs.com/).

**Comment by jcubic** [comment] 2020-10-01 07:02
And don't close the question I will use to update documentation so I don't forget.

**Comment by jcubic** [comment] 2020-10-04 11:06
Webpack was removed from getting started it's now separated page so it's easier to find:

https://github.com/jcubic/jquery.terminal/wiki/Webpack-&-Babel

**Closed by jcubic** 2020-10-04 11:06 UTC
Labels: documentation, question

**Comment by Kingsy** [comment] 2021-01-12 23:29
Hi, sorry to reopen this, however I was hoping you could expand on using jsdom in the above examples? Say I wanted to use the prism extension server side.
How possible is this?
          
        import terminal from "imports-loader?additionalCode=var%20define=false;!jquery.terminal";
        import PrismJS from "prismjs";
        import prism from "imports-loader?additionalCode=var%20define=false;!jquery.terminal/js/prism";

        var jsdom = require("jsdom").jsdom,
            myWindow = jsdom().createWindow(),
            $ = require("jQuery"),
        terminal(window, $);
        prism(myWindow, $, PrismJS);
        
Gives me

        ./node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:4:19
        Module not found: Can't resolve 'child_process'
        null

Any suggestions?
