### ISSUE TITLE
Allow error traceback to be collapsed?

### ISSUE THREAD

**Issue by dragoncoder047** [jcubic/jquery.terminal#787] opened 2022-06-02 12:21 UTC
### I have an idea for a new feature for jQuery Terminal

The `term.exception()` function with an exception object prints out the traceback and turns the file names into clickable links that bring up the line of code that caused the error.

Sometimes the tracebacks are very long and clutter the screen. I want to be able to collapse the traceback in a `<details>` element so it can only be opened if the user wants to see the traceback, otherwise it will only take up one line.

Possibly add an option `{ collapsed: true }` to `exception()` method to do this?

In lieu of this feature I have been doing this: But it does not linkify the file names in the traceback nor does it apply any custom CSS (fonts, colors, etc)

```js
} catch (e) {
    if (e.stack) term.echo(`<details><summary style="color:red">${e.toString()}</summary><pre>${e.stack}</pre></details>`, { raw: true });
}
```

**Comment by dragoncoder047** [comment] 2022-06-02 13:49
Then there is also the problem of CSS too. For some reason the stack inside the `<details>` does not get the custom CSS:
![Screenshot 2022-06-02 9 46 54 AM](https://user-images.githubusercontent.com/101021094/171643992-23f370d1-966f-449a-a2a3-3d703c4ad5f2.png)
![Screenshot 2022-06-02 9 48 00 AM](https://user-images.githubusercontent.com/101021094/171644091-96bc6b6a-1750-454b-9362-00f37fc7abc6.png)

([Here](https://github.com/dragoncoder047/phoo) is the repository where I have this problem.)

**Comment by jcubic** [comment] 2022-06-02 14:06
it's because there is no code that will do that. That's why I suggested what a possible solution can look like.

**Comment by jcubic** [comment] 2022-06-02 14:22
The problem is that raw HTML doesn't have style at all. It works for summary because color and font are inherited but pre have explicit `font-family: monospace` set by the browser.

You need to use:

```css
.terminal pre {
    font-family: monospace;
    font-family: var(--font, monospace);
}
```

**Comment by dragoncoder047** [comment] 2022-06-02 16:25
Great, that appears to work. But the text is still not linkified. And the text is getting bigger and bigger. [I need to fix that](https://github.com/dragoncoder047/phoo/issues/5)

![image](https://user-images.githubusercontent.com/101021094/171677830-7a01910c-5393-4ad1-b09d-5347a70549dc.png)

**Comment by jcubic** [comment] 2022-06-08 07:54
I don't think that it's worth adding this feature to the library. You can just modify the code that is used for printing exceptions:

```javascript
    function exception_message(e) {
        if (typeof e === 'string') {
            return e;
        } else if (typeof e.fileName === 'string') {
            return e.fileName + ': ' + e.message;
        } else {
            return e.message;
        }
    }
    // ...
        function display_exception(e, label, silent) {
            if (is_function(settings.exceptionHandler)) {
                settings.exceptionHandler.call(self, e, label);
            } else {
                self.exception(e, label);
                if (!silent) {
                    setTimeout(function() {
                        throw e;
                    }, 0);
                }
            }
        }
        // ...


            exception: function(e, label) {
                var message = exception_message(e);
                if (label) {
                    message = '&#91;' + label + '&#93;: ' + message;
                }
                if (message) {
                    self.error(message, {
                        finalize: function(div) {
                            div.addClass('terminal-exception terminal-message');
                        },
                        keepWords: true
                    });
                }
                if (typeof e.fileName === 'string') {
                    // display filename and line which throw exeption
                    self.pause(settings.softPause);
                    $.get(e.fileName, function(file) {
                        var num = e.lineNumber - 1;
                        var line = file.split('\n')[num];
                        if (line) {
                            self.error('[' + e.lineNumber + ']: ' + line);
                        }
                        self.resume();
                    }, 'text');
                }
                if (e.stack) {
                    var stack = $.terminal.escape_brackets(e.stack);
                    var output = stack.split(/\n/g).map(function(trace) {
                        // nested formatting will handle urls but that formatting
                        // can be removed - this code was created before
                        // that formatting existed (see commit ce01c3f5)
                        return '[[;;;terminal-error]' +
                            trace.replace(url_re, function(url) {
                                return ']' + url + '[[;;;terminal-error]';
                            }) + ']';
                    }).join('\n');
                    self.echo(output, {
                        finalize: function(div) {
                            div.addClass('terminal-exception terminal-stack-trace');
                        },
                        formatters: false
                    });
                }
                return self;
            },
```

You only need to put message into `<summary>` and use `$.terminal.format()` to get the HTML code out of `output`.

**Comment by jcubic** [comment] 2022-06-08 07:58
The code that echo stuff to the terminal is automatically linking the URLs so you probably want to use `'[[!;;;;' + url + ']' + url + ']'` or ``` `[[!;;;;${url}]${url}]` ```. You need `.terminal-exception` class to be added to `details` so the click will work.

**Comment by jcubic** [comment] 2022-06-12 10:35
I'm closing the issue since it's out of the scope of this project. If you want this to be implemented by me you can get [Paid Support](https://support.jcubic.pl/).

**Closed by jcubic** 2022-06-12 10:35 UTC
Labels: feature, won't fix
