### ISSUE TITLE
Corrupted JSON not error handled in History class

### ISSUE THREAD

**Issue by ZackBotkin** [jcubic/jquery.terminal#210] opened 2015-08-19 15:06 UTC
I have been using the Jquery terminal as a part of a project that I have been working on, and I believe that I have encountered a bug.

In the file jquery.terminal-0.8.8.js, on lines 677-678

    var data = $.Storage.get(storage_key);
    data = data ? $.parseJSON(data) : [];

I am still trying to reproduce the issue, but essentially, I was receiving an error regarding illegal JSON when I attempted to initialize my terminal on the page load. This happened in my firefox browser, but not in chrome, which led me to believe that something was corrupted in my local storage. Sure enough, when I added the following try/catch....

    var data = $.Storage.get(storage_key);
    try {
        data = data ? $.parseJSON(data) : [];
    }
    catch(e) {
        data = [];
    }

...the terminal was able to initialize without a nasty illegal JSON message. This left me wondering how corrupted JSON could be entered into the local storage in the first place. I noticed on line 696,

    $.Storage.set(storage_key, $.json_stringify(data));

It appears that a custom JSON.stringify() function has been defined to stringify the inputted commands.

As I said, I unfortunately am still working on reproducing the issue with a variety of inputs, but I wanted to at least let you guys know that I had experienced this issue. Once I am able to reproduce, I will send screenshots of the error, as well as the offending input or sequence of input/browser actions.

**Comment by jcubic** [comment] 2015-08-19 15:33
Thanks for reporting the bug, I use custom stringify because when I was using original version I've got invalid results when I was using the function with Prototype library that was used by BiwaScheme.

Maybe the problem is when you have history that are larger then the limit of LocalStorage.

**Comment by ZackBotkin** [comment] 2015-08-19 15:38
That would be a good place to start. I'll do my best to break things again and let you know what I come up with. I realize I haven't given you much to go on, other than the quick fix that worked for me.

**Comment by archtimmy** [comment] 2015-08-26 11:30
I can reproduce this bug on Firefox by pressing F12 while the terminal is focused. Nothing happens (the developer console doesn't open, and there is no visible change in the terminal), but the line saved to local storage contains a \0 for each occurence of F12 in the input. This breaks the JSON parser.

**Comment by jcubic** [comment] 2015-08-26 12:34
@archtimmy Fixed in devel branch.

**Closed** 2015-10-18 10:13 UTC
